### ISSUE TITLE
Selecting Title

### ISSUE THREAD

**Issue by MegaKal** [KMKawesoem/Distributed-System-Project#1]
This is our first issue we have to discuss on:
 as teacher says We have actually 4 option to choose 
1. PAROX implementation
2. Distributed File system
3. Akami implementation 
4. RMI

So, what we are expected to on now is choosing one of them and by the next time, come up with possible Ideas based on our choice.

**Comment by MegaKal** [comment]
Here I am suggesting that it would be easier to select RMI since we have some clue about it and we are somehow good at java. We are not expected to study the language. 
So, we can choose a very good idea and implement it.

**Comment by KabiOro** [comment]
> 
> 
> Here I am suggesting that it would be easier to select RMI since we have some clue about it and we are somehow good at java. We are not expected to study the language.
> So, we can choose a very good idea and implement it.

Love your Idea. I am in 100%

**Comment by mikiol60** [comment]
I like it. But We have to come up with a project idea first with RMI so that we know it would be worth it to work on it tho, don't you guys think?

**Comment by mikiol60** [comment]
So let's brainstorm ideas for the night and share tomorrow?

**Comment by MegaKal** [comment]
So, his issue is closed! our next issue is gonna be Selecting a project Idea on RMI
